a=int(input('Enter the first number: '))
b=int(input('Enter the second number: '))
a=int(a)
b=int(b)
print("\t")
print('Addition:',a+b)
print('Subtraction:',a-b)
print('Multiplication:',a*b)
print('Division:',a/b)
